name: Build

on: [push, pull_request]

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Checking formating of all files
        run: |
          terraform fmt -check -diff -recursive

